# Generated by Django 5.0.6 on 2024-06-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superintendencia', models.CharField(default='SP', max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('gerencia', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RGP', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.DateTimeField(verbose_name='date published')),
                ('foto', models.FileField(upload_to='')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materiais.localizacao')),
            ],
        ),
    ]
