# Generated by Django 5.0.6 on 2024-06-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='gerencia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='superintendencia',
            field=models.CharField(default='SP', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='RGP',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
