# Generated by Django 4.2.13 on 2024-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Materiais", "0002_remove_material_descartado_material_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="ativo",
            field=models.BooleanField(default=False, verbose_name="Esta ativo"),
        ),
        migrations.AlterField(
            model_name="material",
            name="servivel",
            field=models.BooleanField(default=True),
        ),
    ]
