# Generated by Django 5.0.6 on 2024-07-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiais', '0002_alter_material_foto1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do Item'),
        ),
    ]
