# Generated by Django 4.2.13 on 2024-08-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Materiais", "0003_alter_material_ativo_alter_material_servivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="codigo_conta",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Código da conta"
            ),
        ),
    ]
