# Generated by Django 4.2.13 on 2024-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Materiais", "0003_alter_material_foto1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizacao",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Em uso"),
        ),
        migrations.AlterField(
            model_name="localizacao",
            name="endereco",
            field=models.TextField(
                blank=True, null=True, verbose_name="Endereço Completo"
            ),
        ),
        migrations.AlterField(
            model_name="localizacao",
            name="gerencia",
            field=models.CharField(max_length=255, verbose_name="Gerência"),
        ),
        migrations.AlterField(
            model_name="localizacao",
            name="obs",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="localizacao",
            name="superintendencia",
            field=models.CharField(
                default="SP", max_length=255, verbose_name="Superintendência"
            ),
        ),
    ]
