# Generated by Django 4.2.13 on 2024-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Materiais",
            "0004_alter_localizacao_ativo_alter_localizacao_endereco_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="RGP",
            field=models.CharField(max_length=255, verbose_name="Numero RGP"),
        ),
    ]
