# Generated by Django 4.2.13 on 2024-08-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Materiais", "0005_alter_material_rgp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="localizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Materiais.localizacao",
                verbose_name="Unidade/Setor",
            ),
        ),
    ]
