# Generated by Django 4.2.13 on 2024-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Materiais", "0006_alter_material_localizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="descartado",
            field=models.BooleanField(default=False, verbose_name="Bem descartado?"),
        ),
    ]
