# Generated by Django 4.2.13 on 2024-07-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="primeiro_acesso",
            field=models.BooleanField(default=True),
        ),
    ]
